Task/Task/Models/Color.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Task_MVC.Models.Base;

namespace Task_MVC.Models
{
    public class Color:BaseEntity
    {
        [Required, StringLength(maximumLength: 20)]
        public string Name { get; set; }
        public List<PlantColor> PlantColors { get; set; }
    }
}

Task/Task/Areas/ProniaAdmin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task_MVC.DAL;
using Task_MVC.Models;

namespace Task.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class ColorController : Controller
    {
        private readonly AppDbContext _context;

        public ColorController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Color> model = _context.Colors.OrderByDescending(x => x.Id).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Color color)
        {
            if (!ModelState.IsValid) return View();
            Color existed = _context.Colors.FirstOrDefault(c => c.Name.ToLower().Trim() == color.Name.ToLower().Trim());
            if (existed != null)
            {
                ModelState.AddModelError("Name", "You can not duplicate category name");
                return View();
            }
            _context.Colors.Add(color);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            if (id is null || id == 0) return NotFound();
            Color color = _context.Colors.FirstOrDefault(c => c.Id == id);
            if (color is null) return NotFound();
            return View(color);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Update(int? id, Color newColor)
        {
            if (id is null || id == 0) return NotFound();
            if (!ModelState.IsValid) return View();

            Color existed = _context.Colors.FirstOrDefault(c => c.Id == id);
            if (existed == null) return NotFound();
            bool duplicate = _context.Colors.Any(c => c.Name == newColor.Name);
            if (duplicate)
            {
                ModelState.AddModelError("Name", "You cannot duplicate name");
                return View();
            }

            _context.Entry(existed).CurrentValues.SetValues(newColor);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Color color = await _context.Colors.FindAsync(id);
            if (color is null) return NotFound();

            _context.Colors.Remove(color);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null || id == 0) return NotFound();
            Color color = await _context.Colors.FindAsync(id);
            if (color is null) return NotFound();
            return View(color);
        }
    }
}

Task/Task/Areas/ProniaAdmin/Views/Color/Create.cshtml
@model Color
@{
    ViewData["Title"] = "Create";
}


<div class="main-panel">
    <h1>Create color</h1>
    <form class="mt-3" method="post">
    <div>
        <label >Color name:</label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mt-2">
        <button class="btn btn-success" type="submit">Create</button>
    </div>
</form>
</div>

Task/Task/Areas/ProniaAdmin/Views/Color/Detail.cshtml
@model Color
@{
    ViewData["Title"] = "Detail";
}
<div class="main-panel">
<h1>Detail</h1> <br/><br/>
<h3>Id: @Model.Id</h3><br/>
<h3>Name: @Model.Name</h3><br/>
</div>

Task/Task/Areas/ProniaAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
    ViewData["Title"] = "Index";
}


<div class="main-panel">
    <div>
        <a class="btn btn-success" asp-area="ProniaAdmin" asp-controller="Color" asp-action="Create">Create new color</a>
    </div>
    <div class="table-responsive pt-3">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Color color in Model)
                {
                    <tr>
                        <td>
                            @color.Id
                        </td>
                        <td>
                            @color.Name
                        </td>
                        <td  class="d-flex">
                                <div>
                                    <a asp-area="ProniaAdmin" asp-controller="Color" asp-action="Update" asp-route-id="@color.Id" class="btn btn-warning"><i class="mdi mdi-border-color"></i></a>
                                </div>
                                <div>
                                    <a class="btn btn-danger" asp-area="ProniaAdmin" asp-controller="Color" asp-action="Delete" asp-route-id="@color.Id"><i class="mdi mdi-delete"></i></a>
                                </div>
                                <div>
                                    <a class="btn btn-primary" asp-area="ProniaAdmin" asp-controller="Color" asp-action="Detail" asp-route-id="@color.Id"><i class="mdi mdi-open-in-new"></i></a>
                                </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Task/Task/Areas/ProniaAdmin/Views/Color/Update.cshtml
@model Color
@{
    ViewData["Title"] = "Update";
}

<div class="main-panel">
    <h1>Edit color</h1>
    <form class="mt-3" method="post">
    <div>
        <label >Color name:</label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mt-2">
        <button class="btn btn-success" type="submit">Edit</button>
    </div>
</form>
</div>