Task/Task/Models/Plant.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Task_MVC.Models.Base;

namespace Task_MVC.Models
{
    public class Plant:BaseEntity
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Desc { get; set; }
        public string SKU { get; set; }
        public int PlantInformationId { get; set; }
        public PlantInformation PlantInformation { get; set; }
        public List<PlantImage> PlantImages { get; set; }
        public List<PlantCategory> PlantCategories { get; set; }
        public List<PlantTag> PlantTags { get; set; }
        public List<PlantColor> PlantColors { get; set; }
        public List<PlantSize> PlantSizes { get; set; }
        [NotMapped]
        public List<int> CategoryIds { get; set; }
        [NotMapped]
        public List<int> TagsIds { get; set; }
        [NotMapped]
        public List<int> ColorsIds { get; set; }
        [NotMapped]
        public List<int> SizesIds { get; set; }
        [NotMapped]
        public List<int> PlantImageIds { get; set; }

        [NotMapped]
        public IFormFile MainPhoto { get; set; }
        [NotMapped]
        public IFormFile HoverPhoto { get; set; }
        [NotMapped]
        public List<IFormFile> Photos { get; set; }
        
    }
}

Task/Task/Areas/ProniaAdmin/Controllers/PlantController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task.Utilities;
using Task_MVC.DAL;
using Task_MVC.Models;

namespace Task.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class PlantController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public PlantController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Plant> model = _context.Plants
                .Include(p => p.PlantInformation)
                .Include(p => p.PlantCategories).ThenInclude(pc => pc.Category)
                .Include(p => p.PlantTags).ThenInclude(pc => pc.Tag)
                .Include(p => p.PlantColors).ThenInclude(pc => pc.Color)
                .Include(p => p.PlantSizes).ThenInclude(pc => pc.Size)
                .Include(p => p.PlantImages).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.Information = _context.PlantInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            ViewBag.Tags = _context.Tags.ToList();
            ViewBag.Colors = _context.Colors.ToList();
            ViewBag.Sizes = _context.Sizes.ToList();
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Plant plant)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                ViewBag.Tags = _context.Tags.ToList();
                ViewBag.Colors = _context.Colors.ToList();
                ViewBag.Sizes = _context.Sizes.ToList();
                return View();
            }
            if (plant.MainPhoto == null || plant.HoverPhoto == null || plant.Photos == null)
            {

                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                ViewBag.Tags = _context.Tags.ToList();
                ViewBag.Colors = _context.Colors.ToList();
                ViewBag.Sizes = _context.Sizes.ToList();
                ModelState.AddModelError(string.Empty, "You must choose 1 main photo and 1 hover photo and 1 another photo");
                return View();
            }

            if (!plant.MainPhoto.ImageIsOkay(2) || !plant.HoverPhoto.ImageIsOkay(2))
            {
                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                ViewBag.Tags = _context.Tags.ToList();
                ViewBag.Colors = _context.Colors.ToList();
                ViewBag.Sizes = _context.Sizes.ToList();
                ModelState.AddModelError(string.Empty, "Please choose valid image file");
                return View();
            }

            TempData["FileName"] = "";
            foreach (var photo in plant.Photos)
            {
                if (!photo.ImageIsOkay(2))
                {
                    plant.Photos.Remove(photo);
                    TempData["FileName"] += photo.FileName + ",";
                }
                else
                {
                    PlantImage other = new PlantImage
                    {
                        Name = await photo.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                        Primary = false,
                        Alternative = plant.Name,
                        Plant = plant
                    };
                    _context.PlantImages.Add(other);
                }
            }

            PlantImage main = new PlantImage
            {
                Name = await plant.MainPhoto.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                Primary = true,
                Alternative = plant.Name,
                Plant = plant
            };
            PlantImage hover = new PlantImage
            {
                Name = await plant.HoverPhoto.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                Primary = null,
                Alternative = plant.Name,
                Plant = plant
            };
            foreach (var item in plant.CategoryIds)
            {
                PlantCategory pCategory = new PlantCategory { 

                CategoryId=item,
                Category=_context.Categories.Find(item),
                PlantId=plant.Id,
                Plant=plant
                
                };
                _context.PlantCategories.Add(pCategory);
            }
            foreach (var item in plant.TagsIds)
            {
                PlantTag pTag = new PlantTag
                {

                    TagId = item,
                    Tag = _context.Tags.Find(item),
                    PlantId = plant.Id,
                    Plant = plant

                };
                _context.PlantTags.Add(pTag);
            }
            foreach (var item in plant.ColorsIds)
            {
                PlantColor pColor = new PlantColor
                {

                    ColorId = item,
                    Color = _context.Colors.Find(item),
                    PlantId = plant.Id,
                    Plant = plant

                };
                _context.PlantColors.Add(pColor);
            }
            foreach (var item in plant.SizesIds)
            {
                PlantSize pSize = new PlantSize
                {

                    SizeId = item,
                    Size = _context.Sizes.Find(item),
                    PlantId = plant.Id,
                    Plant = plant

                };
                _context.PlantSizes.Add(pSize);
            }

            _context.PlantImages.Add(main);
            _context.PlantImages.Add(hover);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            ViewBag.Information = _context.PlantInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            ViewBag.Tags = _context.Tags.ToList();
            ViewBag.Colors = _context.Colors.ToList();
            ViewBag.Sizes = _context.Sizes.ToList();
            if (id == 0 || id is null) return NotFound();
            Plant plant = await _context.Plants.Include(p => p.PlantCategories).ThenInclude(pc => pc.Category).Include(p=>p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            if (plant is null) return NotFound();
            return View(plant);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int? id, Plant plant)
        {
            ViewBag.Information = _context.PlantInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            ViewBag.Tags = _context.Tags.ToList();
            ViewBag.Colors = _context.Colors.ToList();
            ViewBag.Sizes = _context.Sizes.ToList();

            Plant existed = await _context.Plants.Include(p => p.PlantCategories).ThenInclude(pc => pc.Category).Include(p => p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            if (existed is null) return NotFound();
            if (!ModelState.IsValid) {
                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                ViewBag.Tags = _context.Tags.ToList();
                ViewBag.Colors = _context.Colors.ToList();
                ViewBag.Sizes = _context.Sizes.ToList();
                return View(existed); }
                
            if (plant.MainPhoto != null)
            {
                if (!plant.MainPhoto.ImageIsOkay(2))
                {
                    ViewBag.Information = _context.PlantInformations.ToList();
                    ViewBag.Categories = _context.Categories.ToList();
                    ViewBag.Tags = _context.Tags.ToList();
                    ViewBag.Colors = _context.Colors.ToList();
                    ViewBag.Sizes = _context.Sizes.ToList();
                    ModelState.AddModelError("MainPhoto", "Please choose valid image file");
                    return View(existed);
                }
                FileValidator.FileDelete(_env.WebRootPath, "assets/images/website-images", existed.PlantImages.FirstOrDefault(p => p.Primary == true).Name);
                existed.PlantImages.FirstOrDefault(p => p.Primary == true).Name = await plant.MainPhoto.FileCreate(_env.WebRootPath, "assets/images/website-images");
            }
            if (plant.HoverPhoto != null)
            {
                if (!plant.HoverPhoto.ImageIsOkay(2))
                {
                    ViewBag.Information = _context.PlantInformations.ToList();
                    ViewBag.Categories = _context.Categories.ToList();
                    ViewBag.Tags = _context.Tags.ToList();
                    ViewBag.Colors = _context.Colors.ToList();
                    ViewBag.Sizes = _context.Sizes.ToList();
                    ModelState.AddModelError("MainPhoto", "Please choose valid image file");
                    return View(existed);
                }
                FileValidator.FileDelete(_env.WebRootPath, "assets/images/website-images", existed.PlantImages.FirstOrDefault(p => p.Primary == null).Name);

                existed.PlantImages.FirstOrDefault(p => p.Primary == null).Name = await plant.HoverPhoto.FileCreate(_env.WebRootPath, "assets/images/website-images");
            }
            if (plant.PlantImageIds == null)
            {

Task/Task/Controllers/PlantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task_MVC.ViewModels;
using Task_MVC.DAL;
using Task_MVC.Models;
using Task.Models;
using Microsoft.AspNetCore.Identity;

namespace Task_MVC.Controllers
{
    public class PlantController:Controller
    {

        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public PlantController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }
            Plant plant = await _context.Plants.Include(p => p.PlantImages)
                .Include(p => p.PlantInformation).Include(p => p.PlantCategories).ThenInclude(p => p.Category).Include(p=>p.PlantTags).ThenInclude(p=>p.Tag)
                .Include(p => p.PlantColors).ThenInclude(p => p.Color).Include(p => p.PlantSizes).ThenInclude(p => p.Size).FirstOrDefaultAsync(p => p.Id == id);
            List<Plant> plants = new List<Plant>();
            List<Plant> plantsRange = new List<Plant>();
            foreach (var item in plant.PlantCategories)
            {
                plants = _context.Plants.Where(x=>x.Id!=id).Where(x => x.PlantCategories.Any(z => z.CategoryId == item.CategoryId)).Include(x => x.PlantImages).ToList();

                plantsRange.AddRange(plants);
            }
            PlantVM plantVM = new PlantVM
            {
                Plant=plant,
                Plants= plantsRange.Distinct().ToList(),
            };
          
            if (plant is null) return NotFound();

            return View(plantVM);
        }
        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
            {
                AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (user == null) return NotFound();
                BasketItem existed = await _context.BasketItems.FirstOrDefaultAsync(b => b.AppUserId == user.Id && b.PlantId == plant.Id);
                if (existed == null)
                {
                    existed = new BasketItem
                    {
                        Plant = plant,
                        AppUser = user,
                        Quantity = 1,
                        Price = plant.Price
                    };
                    _context.BasketItems.Add(existed);
                }
                else
                {
                    existed.Quantity++;
                }
                await _context.SaveChangesAsync();
            }
            else
            {
                string basketStr = HttpContext.Request.Cookies["Basket"];

                BasketVM basket;

                if (string.IsNullOrEmpty(basketStr))
                {
                    basket = new BasketVM();
                    BasketCookieItemVM cookieItem = new BasketCookieItemVM
                    {
                        Id = plant.Id,
                        Quantity = 1
                    };
                    basket.BasketCookieItemVMs = new List<BasketCookieItemVM>();
                    basket.BasketCookieItemVMs.Add(cookieItem);
                    basket.TotalPrice = plant.Price;

                }
                else
                {
                    basket = JsonConvert.DeserializeObject<BasketVM>(basketStr);
                    BasketCookieItemVM existed = basket.BasketCookieItemVMs.Find(p => p.Id == id);
                    if (existed == null)
                    {
                        BasketCookieItemVM cookieItem = new BasketCookieItemVM
                        {
                            Id = plant.Id,
                            Quantity = 1
                        };
                        basket.BasketCookieItemVMs.Add(cookieItem);
                        basket.TotalPrice += plant.Price;
                    }
                    else
                    {
                        basket.TotalPrice += plant.Price;
                        existed.Quantity++;
                    }
                }
                basketStr = JsonConvert.SerializeObject(basket);

                HttpContext.Response.Cookies.Append("Basket", basketStr);
            }

            return RedirectToAction("Index", "Home");
        }



        public IActionResult ShowBasket()
        {
            if (HttpContext.Request.Cookies["Basket"] == null) return NotFound();
            BasketVM basket = JsonConvert.DeserializeObject<BasketVM>(HttpContext.Request.Cookies["Basket"]);
            return Json(basket);
        }
        public async Task<IActionResult> RemoveBasket(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            string basketStr = HttpContext.Request.Cookies["Basket"];

            BasketVM basket;

            if (string.IsNullOrEmpty(basketStr))
            {
               return NotFound();
            }
            else
            {
                basket = JsonConvert.DeserializeObject<BasketVM>(basketStr);
                BasketCookieItemVM existed = basket.BasketCookieItemVMs.Find(p => p.Id == id);
                if (existed == null)
                {
                    return NotFound();
                }
                else
                {
                    basket.TotalPrice -= existed.Quantity*plant.Price;
                    basket.BasketCookieItemVMs.Remove(existed);
                }
            }
            basketStr = JsonConvert.SerializeObject(basket);

            HttpContext.Response.Cookies.Append("Basket", basketStr);

            return RedirectToAction("Index", "Home");
        }

    }
}

Task/Task/Areas/ProniaAdmin/Views/Plant/Create.cshtml
@model Plant
@{
    ViewData["Title"] = "Create";
}


<div class="main-panel">
    <h1>Create plant</h1>
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form class="mt-3" method="post" enctype="multipart/form-data">
         <div>
        <label >Main:</label><br />
        <input asp-for="MainPhoto" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="MainPhoto"></span>
    </div>
     <div>
        <label >Hover:</label><br />
        <input asp-for="HoverPhoto" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="HoverPhoto"></span>
    </div>
    <div>
        <label >Images:</label><br />
        <input asp-for="Photos" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Photos"></span>
    </div>
    <div>
        <label >Name:</label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label >Price:</label><br />
        <input asp-for="Price" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label >Description:</label><br />
        <input asp-for="Desc" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Desc"></span>
    </div>
    <div>
        <label >SKU:</label><br />
        <input asp-for="SKU" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="SKU"></span>
    </div>
    <div>
        <label >Plant Information:</label><br />
        <select class="form-control" asp-for="PlantInformationId" asp-items="@(new SelectList(ViewBag.Information,"Id","Shipping"))"></select>
    </div>
     <div>
        <label >Plant Categories:</label><br />
        <select class="form-control" asp-for="CategoryIds" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"></select>
    </div>
     <div>
        <label >Plant Tags:</label><br />
        <select class="form-control" asp-for="TagsIds" asp-items="@(new SelectList(ViewBag.Tags,"Id","Name"))"></select>
    </div>
     <div>
        <label >Plant Colors:</label><br />
        <select class="form-control" asp-for="ColorsIds" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))"></select>
    </div>
     <div>
        <label >Plant Sizes:</label><br />
        <select class="form-control" asp-for="SizesIds" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))"></select>
    </div>
    <div class="mt-2">
        <button class="btn btn-success" type="submit">Create</button>
    </div>
</form>
</div>

Task/Task/Areas/ProniaAdmin/Views/Plant/Index.cshtml
@model List<Plant>
@{
    ViewData["Title"] = "Index";
}


<div class="main-panel">
    <div>
        <a class="btn btn-success" asp-area="ProniaAdmin" asp-controller="Plant" asp-action="Create">Create new plant</a>
    </div>
    <div class="table-responsive pt-3">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        SKU
                    </th>
                    <th>
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Plant plant in Model)
                {
                    <tr>
                        <td>
                            <img style="width:150px !important; height:150px; object-fit:contain" src="~/assets/images/website-images/@plant.PlantImages.FirstOrDefault(p=>p.Primary == true)?.Name" alt="">
                        </td>
                        <td>
                            @plant.Name
                        </td>
                         <td>
                            @plant.Price
                        </td>
                        <td>
                            @plant.SKU
                        </td>
                        <td  class="d-flex">
                                <div>
                                    <a asp-area="ProniaAdmin" asp-controller="plant" asp-action="Update" asp-route-id="@plant.Id" class="btn btn-warning"><i class="mdi mdi-border-color"></i></a>
                                </div>
                                <div>
                                    <a class="btn btn-danger" asp-area="ProniaAdmin" asp-controller="plant" asp-action="Delete" asp-route-id="@plant.Id"><i class="mdi mdi-delete"></i></a>
                                </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Task/Task/Areas/ProniaAdmin/Views/Plant/Update.cshtml
@model Plant
@{
    ViewData["Title"] = "Update";
}


<div class="main-panel">
    <h1>Edit plant</h1>
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form class="mt-3" method="post" enctype="multipart/form-data">
        <div>
            <div class="image my-3">
                <img width="300" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p=>p.Primary==true).Name">
            </div>
            <label>Main:</label><br />
            <input asp-for="MainPhoto" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="MainPhoto"></span>
        </div>
        <div>
            <div class="image my-3">
                <img width="300" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p=>p.Primary==null).Name">
            </div>
            <label>Hover:</label><br />
            <input asp-for="HoverPhoto" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="HoverPhoto"></span>
        </div>
        <div>
                @foreach (var item in Model.PlantImages.Where(p => p.Primary == false))
                {
                    <div>
                       <button class="remove">X</button>
                        <img width="300" src="~/assets/images/website-images/@item.Name">
                        <input name="PlantImageIds" type="hidden" class="form-control" value="@item.Id" /><br />
                        <span class="text-danger" asp-validation-for="PlantImageIds"></span>
                    </div>
                }
            </div>
        <div>
            <label>Images:</label><br />
            <input asp-for="Photos" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Photos"></span>
        </div>
        <div>
            <label>Name:</label><br />
            <input asp-for="Name" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div>
            <label>Price:</label><br />
            <input asp-for="Price" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>
        <div>
            <label>Description:</label><br />
            <input asp-for="Desc" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Desc"></span>
        </div>
        <div>
            <label>SKU:</label><br />
            <input asp-for="SKU" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="SKU"></span>
        </div>
           <div>
        <label >Plant Information:</label><br />
        <select class="form-control" asp-for="PlantInformationId" asp-items="@(new SelectList(ViewBag.Information,"Id","Shipping"))"></select>
        </div>
        <div>
        <label >Plant Categories:</label><br />
         <select class="form-control" asp-for="CategoryIds">
                @foreach (Category category in ViewBag.Categories)
                {
                    if (Model.PlantCategories.Exists(p => p.CategoryId == category.Id))
                    {
                        <option value="@category.Id" selected>@category.Name</option>
                    }
                    else
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                }
            </select>
             <span class="text-danger" asp-validation-for="CategoryIds"></span>
        </div>
        <div class="mt-2">
            <button class="btn btn-success" type="submit">Edit</button>
        </div>
    </form>
</div>

<script>
    //const child = document.getElementsByClassName("custom-delete");

    //for (let i = 0; i < child.length; i++) {
    //     child[i].onclick = function() { 
    //     child[i].parentElement.remove()
    //         child[i].remove();
    //     };
    //}
    function registerClickHandler (e) {
  // Implement the click handler here for button of class 'remove'
  var target = e.target;
  target.parentNode.parentNode.removeChild(target.parentNode);
}

var removeBtn = document.querySelectorAll('.remove');

for (var i = 0 ; i < removeBtn.length; i++) {
   removeBtn[i].addEventListener("click", registerClickHandler, false); 
}
</script>